import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Fullstack Web Development",
    company: "LearningX MSIB Studi Independen",
    logo: "/images/careers/learningx.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Hybrid",
    type: "Internship",
    start_date: "2024-01",
    end_date: "2024-06",
    industry: "Education/Technology",
    link: "https://www.learningx.com/",
    responsibilities: [
      "Developed multiple web applications during the Independent Study Full-Stack Web Development Program (MSIB Batch 6), including a portfolio website, movie database, interactive vocabulary builder, and an online school registration system.",
      "Built backend services using Flask and MongoDB, handling user registration, document uploads, and secure data storage.",
      "Implemented responsive and user-friendly interfaces using HTML, CSS, JavaScript, and Bootstrap.",
    ],
    lessons_learned: [
      "Strengthened understanding of full-stack web development concepts, including frontend–backend integration.",
      "Gained hands-on experience in backend development using Flask and NoSQL database management with MongoDB.",
      "Learned to implement API integration to extend application features and improve system interoperability.",
    ],
    impact: [
      "Successfully delivered a web-based school registration system enabling online student enrollment, document uploads, and secure data management.",
      "Improved efficiency of data processing and accessibility through structured backend logic and database design.",
      "Produced functional, maintainable, and scalable web applications aligned with real-world use cases.",
    ],
    isShow: true,
  },
  {
    position: "Data Entry Staff",
    company: "Pt. Pejuang Indonesia Cerdas",
    logo: "/images/careers/pejuang-indonesia-cerdas.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Internship",
    start_date: "2025-04",
    end_date: "2025-06",
    industry: "Education/Technology",
    link: "https://pejuangosn.com/",
    responsibilities: [
      "Managed and input thousands of tryout questions for national OSN preparation programs used by 1,500+ participants from various regions.",
      "Ensured accurate data entry by organizing questions based on subjects and difficulty levels with high attention to detail.",
      "Utilized Microsoft Excel and Google Sheets to structure, verify, and validate question data.",
    ],
    lessons_learned: [
      "Strengthened skills in data management and validation, ensuring consistency and accuracy across large datasets.",
      "Improved ability to work efficiently under pressure while maintaining high data quality.",
    ],
    impact: [
      "Supported the successful execution of national tryout programs for more than 1,500 participants.",
      "Improved data reliability by maintaining well-structured and validated question databases.",
    ],
    isShow: true,
  },
  {
    position: "Fullstack Web Development",
    company: "PT Indocyber Global Teknologi",
    logo: "/images/careers/indocyber-global-teknologi.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2025-09",
    end_date: "2025-10",
    industry: "Technology",
    link: "https://www.indocyber.co.id/",
    responsibilities: [
      "Worked extensively in database engineering using SQL Server, starting from analyzing existing database scripts.",
      "Designed Entity Relationship Diagrams (ERD) as a foundation for database development.",
      "Implemented databases in SQL Server based on the approved ERD designs.",
      "Created and maintained SQL scripts for database creation and management.",
    ],
    lessons_learned: [
      "Gained a strong understanding of relational database design, normalization, and structured data modeling.",
      "Improved proficiency in SQL Server scripting, including table creation and database structuring.",
    ],
    impact: [
      "Successfully designed and implemented structured and well-documented databases using SQL Server.",
      "Improved database clarity and maintainability through proper ERD-based design.",
      "Developed a strong technical foundation in database engineering and programming logic, supporting future full-stack development work.",
    ],
    isShow: true,
  },
  {
    position: "Systems Analyst and Development (MagangHub)",
    company: "Kementrian Keuangan",
    logo: "/images/careers/kementrian-keuangan.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2025-12",
    end_date: "2026-06",
    industry: "Education/Technology",
    link: "https://www.kemenkeu.go.id/",
    responsibilities: [
      "Developed a web-based Employee Management Information System (JFAA) using Express.js, Vue.js, and MySQL, with a primary focus on backend development.",
      "Designed and implemented RESTful APIs, including database schema design, business logic, authentication & authorization, and environment configuration (.env).",
      "Documented and tested APIs using Swagger and Postman, and managed version control and collaboration through GitHub.",
    ],
    lessons_learned: [
      "Strengthened understanding of backend architecture and RESTful API development with Express.js.",
      "Gained practical experience in relational database design and management using MySQL.",
      "Learned industry practices in API documentation, testing, security, and version control.",
    ],
    impact: [
      "Delivered a scalable and maintainable backend system for employee data management.",
      "Enabled smooth frontend–backend integration through well-documented and reliable APIs.",
      "Improved system reliability, data consistency, and security to support continuous system development.",
    ],
    isShow: true,
  },
  {
    position: "Business Analyst",
    company: "Indivara Group",
    logo: "/images/careers/indivara.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2026-06",
    end_date: "2026-08",
    industry: "Information Technology",
    link: "https://www.indivaragroup.com/",
    responsibilities: [
      "Analyzed business needs and compiled Business Requirement Documents (BRD) as well as User Requirements as a foundation for application development across various domains.",
      "Designed Activity Diagrams, Use Case Diagrams, and End-to-End Business Processes to model business workflows and align solutions with stakeholder requirements.",
      "Prepared Functional Specification Documents (FSD) detailing functional requirements, business rules, and system specifications to guide UI/UX designers, developers, and QA engineers.",
    ],
    lessons_learned: [
      "Deepened expertise in business process modeling, requirement gathering, and translating complex business needs into actionable technical specifications.",
      "Enhanced cross-functional collaboration and communication skills across UI/UX, engineering, QA, and business stakeholders.",
      "Mastered industry-standard documentation practices (BRD, FSD, Use Case, Activity Diagrams) ensuring seamless development alignment.",
    ],
    impact: [
      "Established clear and standardized project documentation (BRD & FSD) that significantly reduced ambiguity and alignment friction between business stakeholders and technical teams.",
      "Streamlined the software development lifecycle by providing precise business logic, use cases, and functional specifications to UI/UX, Developers, and QA.",
      "Ensured end-to-end delivery of high-quality software solutions tailored to complex business requirements.",
    ],
    isShow: true,
  },
];
